name: supabase
description: A dart client for Supabase. This client makes it simple for developers to build secure and scalable products.
<<<<<<< HEAD
version: 2.0.0-dev.1
=======
version: 1.11.11
>>>>>>> main
homepage: 'https://supabase.com'
repository: 'https://github.com/supabase/supabase-flutter/tree/main/packages/supabase'
documentation: 'https://supabase.com/docs/reference/dart/introduction'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
<<<<<<< HEAD
  functions_client: ^2.0.0-dev.0
  gotrue: ^2.0.0-dev.0
  http: '>=0.13.5 <2.0.0'
  postgrest: ^2.0.0-dev.0
  realtime_client: ^2.0.0-dev.1
  storage_client: ^2.0.0-dev.0
=======
  functions_client: ^1.3.2
  gotrue: ^1.12.6
  http: '>=0.13.5 <2.0.0'
  postgrest: ^1.5.2
  realtime_client: ^1.4.0
  storage_client: ^1.5.4
>>>>>>> main
  rxdart: ^0.27.5
  yet_another_json_isolate: ^2.0.0-dev.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.17.9
  web_socket_channel: ^2.2.0
