name: supabase
description: A dart client for Supabase. This client makes it simple for developers to build secure and scalable products.
version: 1.8.1
homepage: 'https://supabase.com'
repository: 'https://github.com/supabase/supabase-flutter/tree/main/packages/supabase'
documentation: 'https://supabase.com/docs/reference/dart/introduction'

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  functions_client: ^1.2.1
  gotrue: ^1.7.1
  http: ^0.13.4
  postgrest: ^1.2.4
  realtime_client: ^1.0.4
  storage_client: ^1.3.1
  rxdart: ^0.27.5
  yet_another_json_isolate: ^1.0.4

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.9
  web_socket_channel: ^2.2.0
