name: supabase_flutter
description: Flutter integration for Supabase. This package makes it simple for developers to build secure and scalable products.
version: 1.8.1
homepage: 'https://supabase.io'
repository: 'https://github.com/supabase/supabase-flutter'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  app_links: ^3.4.1
  crypto: ^3.0.2
  flutter:
    sdk: flutter
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  http: ^0.13.4
  meta: ^1.7.0
  sign_in_with_apple: ^4.3.0
  supabase: ^1.6.1
  url_launcher: ^6.1.2
  webview_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

platforms:
  android:
  ios:
  macos:
  web:
  windows:

flutter:
