name: supabase_flutter
description: Flutter integration for Supabase. This package makes it simple for developers to build secure and scalable products.
version: 1.10.14
homepage: 'https://supabase.com'
repository: 'https://github.com/supabase/supabase-flutter/tree/main/packages/supabase_flutter'
documentation: 'https://supabase.com/docs/reference/dart/introduction'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  app_links: ^3.4.1
  crypto: ^3.0.2
  flutter:
    sdk: flutter
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  http: '>=0.13.4 <2.0.0'
  meta: ^1.7.0
  sign_in_with_apple: '>=4.3.0 <6.0.0'
  supabase: ^1.11.1
  url_launcher: ^6.1.2
  webview_flutter: ^4.0.0
  path_provider: ^2.0.0
  shared_preferences: ^2.0.0

dev_dependencies:
  dart_jsonwebtoken: ^2.4.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

platforms:
  android:
  ios:
  macos:
  web:
  windows:

flutter:
