name: Publish storage_client to pub.dev

on:
  push:
    tags:
      - 'storage_client-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: packages/storage_client
