name: storage_client

on:
  push:
    paths:
      - 'packages/storage_client/**'
      - '.github/workflows/storage_client.yaml'
  pull_request:
    paths:
      - 'packages/storage_client/**'
      - '.github/workflows/storage_client.yaml'

jobs:
  test:
    name: storage_client Test / SDK ${{ matrix.sdk }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: ['12']
        sdk: [2.15.0, stable, beta, dev]

    defaults:
      run:
        working-directory: packages/storage_client

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checks-out repo
        uses: actions/checkout@v2

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: dartfmt
        run: dart format lib test -l 80 --set-exit-if-changed

      - name: analyzer
        run: dart analyze --fatal-warnings --fatal-infos .

      - name: Build Docker image
        run: |
          cd infra
          docker-compose down
          docker-compose up -d

      - name: Sleep for 5 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'

      - name: Run tests
        run: dart test
