# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test / Flutter Version ${{ matrix.flutter-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        flutter-version: ['3.0.0', '3.x']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checks-out repo
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ matrix.flutter-version }}
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: flutterfmt
        run: dart format lib test -l 80 --set-exit-if-changed

      - name: analyzer
        run: flutter analyze --fatal-warnings --fatal-infos .

      - name: Run tests
        run: flutter test
