name: Publish supabase_flutter to pub.dev

on:
  push:
    tags:
      - 'supabase_flutter-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    name: Publish on pub.dev
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/supabase_flutter

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      # This step adds the auth token for pub.dev
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get
      - name: Publish - dry run
        run: flutter pub publish --dry-run
      # Publishing...
      - name: Publish to pub.dev
        run: flutter pub publish -f