name: supabase

on:
  push:
    paths:
      - 'packages/supabase/**'
      - '.github/workflows/supabase.yaml'

  pull_request:
    paths:
      - 'packages/supabase/**'
      - '.github/workflows/supabase.yaml'

jobs:
  test:
    name: supabase Test / SDK ${{ matrix.sdk }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: ['12']
        sdk: [2.15.0, stable, beta, dev]

    defaults:
      run:
        working-directory: packages/supabase

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checks-out repo
        uses: actions/checkout@v2

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: dartfmt
        run: dart format lib test -l 80 --set-exit-if-changed

      - name: analyzer
        run: dart analyze --fatal-warnings --fatal-infos .

      - name: Run tests
        run: dart test
