name: Publish yet_another_json_isolate to pub.dev

on:
  push:
    tags:
      - 'yet_another_json_isolate-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: packages/yet_another_json_isolate
